# Generated by Django 6.0.5 on 2026-05-17 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsSalt",
            fields=[
                (
                    "day",
                    models.DateField(
                        db_column="day", primary_key=True, serialize=False
                    ),
                ),
                ("salt", models.CharField(db_column="salt", max_length=64)),
            ],
            options={
                "db_table": "analytics_salt",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("code", models.CharField(db_column="code", max_length=64)),
                (
                    "display_name",
                    models.CharField(db_column="display_name", max_length=128),
                ),
                ("sort_order", models.IntegerField(db_column="sort_order", default=0)),
            ],
            options={
                "db_table": "category",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField(db_column="year", unique=True)),
                ("name", models.CharField(db_column="name", max_length=128)),
                (
                    "slug",
                    models.CharField(db_column="slug", max_length=64, unique=True),
                ),
                (
                    "is_current",
                    models.BooleanField(db_column="is_current", default=False),
                ),
                (
                    "championship_format",
                    models.CharField(
                        db_column="championship_format",
                        default="per_event",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "db_table": "season",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "source_filename",
                    models.CharField(db_column="source_filename", max_length=255),
                ),
                ("sha256", models.CharField(db_column="sha256", max_length=64)),
                ("imported_at", models.DateTimeField(db_column="imported_at")),
                (
                    "rows_imported",
                    models.IntegerField(db_column="rows_imported", default=0),
                ),
            ],
            options={
                "db_table": "import_log",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["source_filename"], name="ix_import_log_filename"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_filename", "sha256"),
                        name="uq_import_log_file_sha",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("race_number", models.IntegerField(db_column="race_number")),
                (
                    "first_name",
                    models.CharField(db_column="first_name", max_length=128),
                ),
                ("last_name", models.CharField(db_column="last_name", max_length=128)),
                (
                    "team",
                    models.CharField(
                        blank=True, db_column="team", max_length=255, null=True
                    ),
                ),
                (
                    "bike",
                    models.CharField(
                        blank=True, db_column="bike", max_length=255, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riders",
                        to="core.category",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        db_column="season_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riders",
                        to="core.season",
                    ),
                ),
            ],
            options={
                "db_table": "rider",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("slug", models.CharField(db_column="slug", max_length=64)),
                ("name", models.CharField(db_column="name", max_length=128)),
                (
                    "event_date",
                    models.DateField(blank=True, db_column="event_date", null=True),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="location", max_length=128, null=True
                    ),
                ),
                ("sort_order", models.IntegerField(db_column="sort_order", default=0)),
                (
                    "event_type",
                    models.CharField(
                        blank=True, db_column="event_type", max_length=64, null=True
                    ),
                ),
                (
                    "facebook_event_url",
                    models.CharField(
                        blank=True,
                        db_column="facebook_event_url",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "season",
                    models.ForeignKey(
                        db_column="season_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.season",
                    ),
                ),
            ],
            options={
                "db_table": "event",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="category",
            name="season",
            field=models.ForeignKey(
                db_column="season_id",
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="core.season",
            ),
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField(db_column="timestamp")),
                ("page", models.CharField(db_column="page", max_length=64)),
                (
                    "category",
                    models.CharField(
                        blank=True, db_column="category", max_length=64, null=True
                    ),
                ),
                (
                    "season_year",
                    models.IntegerField(blank=True, db_column="season_year", null=True),
                ),
                (
                    "device_type",
                    models.CharField(
                        db_column="device_type", default="unknown", max_length=16
                    ),
                ),
                (
                    "visitor_id",
                    models.CharField(db_column="visitor_id", default="", max_length=32),
                ),
                (
                    "session_id",
                    models.CharField(db_column="session_id", default="", max_length=36),
                ),
                (
                    "event_slug",
                    models.CharField(
                        blank=True, db_column="event_slug", max_length=64, null=True
                    ),
                ),
                (
                    "rider_slug",
                    models.CharField(
                        blank=True, db_column="rider_slug", max_length=128, null=True
                    ),
                ),
                (
                    "compared_with_slug",
                    models.CharField(
                        blank=True,
                        db_column="compared_with_slug",
                        max_length=128,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "visit",
                "managed": True,
                "indexes": [
                    models.Index(fields=["timestamp"], name="ix_visit_timestamp"),
                    models.Index(
                        fields=["visitor_id", "timestamp"], name="ix_visit_visitor_time"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventResult",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("day", models.IntegerField(db_column="day", default=1)),
                (
                    "position",
                    models.IntegerField(blank=True, db_column="position", null=True),
                ),
                (
                    "points",
                    models.DecimalField(
                        blank=True,
                        db_column="points",
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "time_ms",
                    models.BigIntegerField(blank=True, db_column="time_ms", null=True),
                ),
                (
                    "start_time_ms",
                    models.BigIntegerField(
                        blank=True, db_column="start_time_ms", null=True
                    ),
                ),
                (
                    "gps_penalty_ms",
                    models.BigIntegerField(
                        blank=True, db_column="gps_penalty_ms", null=True
                    ),
                ),
                (
                    "cp_penalty_ms",
                    models.BigIntegerField(
                        blank=True, db_column="cp_penalty_ms", null=True
                    ),
                ),
                (
                    "cp_count",
                    models.IntegerField(blank=True, db_column="cp_count", null=True),
                ),
                ("laps", models.IntegerField(blank=True, db_column="laps", null=True)),
                (
                    "gap_ms",
                    models.BigIntegerField(blank=True, db_column="gap_ms", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="status", max_length=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="notes", null=True)),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.event",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        db_column="rider_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.rider",
                    ),
                ),
            ],
            options={
                "db_table": "event_result",
                "managed": True,
                "indexes": [
                    models.Index(fields=["event"], name="ix_result_event"),
                    models.Index(fields=["rider"], name="ix_result_rider"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "rider", "day"),
                        name="uq_result_event_rider_day",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rider",
            constraint=models.UniqueConstraint(
                fields=("category", "race_number"), name="uq_rider_category_race_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("season", "slug"), name="uq_event_season_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("season", "code"), name="uq_category_season_code"
            ),
        ),
    ]
