"""
==============================================================================
  FROZEN BY F1 — DO NOT EDIT THIS FILE IN ANY SLICE TASK (decision I1-arch=A)
==============================================================================

The single ``NinjaAPI`` instance and the FULL router assembly are written
ONCE here, with EVERY domain + cross-cutting router slot pre-stubbed as an
empty placeholder ``Router``. This is a deliberate shared-write hotspot
eliminator: with all slots declared up front, parallel slice agents never
touch this file (or ``config/urls.py``) — they fill ONLY their own
``api/<domain>.py`` module. A bad merge that reorders this assembly is a
total-API-outage failure mode (see ``.plan/django-ninja-tasks.md`` Failure
modes + CLAUDE.md mount-order invariant #4).

RULES FOR SLICE AGENTS (S1–S7, X1–X3):
  • NEVER edit this file. NEVER reorder ``add_router`` calls.
  • Fill only the body of your own ``api/<domain>.py`` (or ``redirects/``,
    ``core/admin.py``, ``api/docs.py`` for the X-slices).
  • The router objects below are imported by reference; replacing the empty
    ``Router()`` with a populated one in your module is all you do.

ROUTER SLOT INVENTORY (all pre-stubbed, all empty in F1):
  S1  seasons        api.seasons.router            → /api/seasons/*
  S2  standings      api.standings.router          → /api/seasons/*  (leaderboard)
  S3  events         api.events.router             → /api/seasons/*  (races)
  S7  results        api.results.router            → /api/seasons/*  (race results)
  S4  riders         api.riders.router             → /api/seasons/*  (per-season)
  S4  riders-career  api.riders.career_router      → /api/riders/*   (career+search)
  S5  stats          api.stats.router              → /api/*          (stats, auth-gated)
  S6  track          api.track.router              → /api/*          (analytics write)

  X2  docs/openapi   api.docs.gated_docs_urlpatterns  (wired in config/urls.py)
  X1  redirects      redirects.legacy_redirect_urlpatterns + static_catchall
                                                      (wired in config/urls.py)
  X3  admin          django.contrib.admin             (wired in config/urls.py)

The Ninja-router band (S1–S7) is assembled here. The cross-cutting slots
(X1 legacy 301s, X2 gated docs, X3 admin) live in the URLconf because they
are not Ninja routers; F1 also froze ``config/urls.py`` so the load-bearing
resolution order ( /api/* → /health → /admin → legacy 301s → static ) is
written exactly once. See that file's header.

The prefixes below mirror the frozen FastAPI app's mount points
(``backend/app/main.py:107-114``) EXACTLY so the public URL surface is
byte-identical. ``urls_namespace="api"`` keeps this instance's URL names
isolated. Serialization-renderer pinning + the JSON parity contract are F3's
responsibility (not re-decided here) — F1 only freezes structure + order.
"""

from ninja import NinjaAPI

from api import events as events_api
from api import results as results_api
from api import riders as riders_api
from api import seasons as seasons_api
from api import standings as standings_api
from api import stats as stats_api
from api import track as track_api

# Single API instance. docs/openapi are deliberately handled by X2 behind the
# stats auth gate (parity with backend/app/main.py:70-81 docs_url=None) — so
# the built-in docs are disabled here and re-mounted gated in config/urls.py.
api = NinjaAPI(
    title="BGX Hard Enduro Dashboard API",
    version="0.1.0",  # == settings.APP_VERSION; F3 may centralize the source.
    description="Read-only JSON API for the BGX Hard Enduro Championship",
    urls_namespace="api",
    docs_url=None,
    openapi_url=None,
)

# -- FROZEN router assembly -------------------------------------------------
# Order + prefixes mirror backend/app/main.py:107-114 exactly. Do NOT reorder.
# Every router below is an empty placeholder in F1; slices fill their module.
api.add_router("/seasons", seasons_api.router, tags=["seasons"])         # S1
api.add_router("/seasons", standings_api.router, tags=["leaderboard"])   # S2
api.add_router("/seasons", events_api.router, tags=["races"])            # S3
api.add_router("/seasons", results_api.router, tags=["race-results"])    # S7
api.add_router("/seasons", riders_api.router, tags=["riders"])           # S4
api.add_router("/riders", riders_api.career_router, tags=["riders"])     # S4
api.add_router("", stats_api.router, tags=["stats"])                     # S5
api.add_router("", track_api.router, tags=["track"])                     # S6
# -- END FROZEN router assembly --------------------------------------------

__all__ = ["api"]
