/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_api_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season Detail */
        get: operations["get_season_detail_api_seasons__year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/standings/{category_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_api_seasons__year__standings__category_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Races */
        get: operations["list_races_api_seasons__year__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/events/{event_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Race Detail */
        get: operations["get_race_detail_api_seasons__year__events__event_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/categories/{category_code}/events/{event_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Race Results */
        get: operations["get_race_results_api_seasons__year__categories__category_code__events__event_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/riders/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Riders
         * @description Case-insensitive substring match on first_name, last_name, race_number.
         *
         *     Returns at most `limit` results, ranked by best-match heuristic:
         *       1. exact race_number match (numeric query) first;
         *       2. then last_name prefix match;
         *       3. then first_name prefix match;
         *       4. then everything else.
         */
        get: operations["search_riders_api_seasons__year__riders_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/riders/{race_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Riders Sharing Number
         * @description Returns every (first, last) pair sharing ``race_number`` in this season.
         *
         *     Use case: when multiple people race with the same number (common when a
         *     number is shared across categories or reissued), the frontend shows a
         *     disambiguation page before resolving to a singular rider.
         */
        get: operations["list_riders_sharing_number_api_seasons__year__riders__race_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/riders/{race_number}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rider
         * @description Resolves the rider matching (season, race_number, slug) to a full profile.
         *
         *     404 if the race_number doesn't exist in the season, the slug doesn't match any
         *     (first, last) pair with that number, or the rider has no results.
         */
        get: operations["get_rider_api_seasons__year__riders__race_number___slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/riders/career": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rider Career
         * @description Multi-season career view for a rider (P3 #17).
         *
         *     Match key is the computed slug (`first-last`, lowercased,
         *     spaces→hyphens). Every Rider row whose computed slug equals the
         *     query is grouped by (season_year, category) and aggregated.
         *
         *     Why slug, not (race_number, name)? A rider can change race numbers
         *     between seasons but the name stays. Slug is the most stable
         *     identifier we have without explicit person-IDs.
         *
         *     Edge: two unrelated people with identical names will collide.
         *     Acceptable in practice for this domain.
         */
        get: operations["get_rider_career_api_riders_career_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/riders/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Riders Global
         * @description Cross-season rider search.
         *
         *     Same tokenization rules as the per-season endpoint above (whitespace-
         *     AND across tokens, each token ORs across first_name / last_name /
         *     race_number). Results are deduped by computed slug — riders who
         *     raced multiple seasons appear once with their most recent
         *     (year, category). UI links to /rider/{slug}, which is multi-season
         *     by design, so showing every (year, category) row would just be noise.
         */
        get: operations["search_riders_global_api_riders_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Track Visit */
        post: operations["track_visit_api_track_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryRef */
        CategoryRef: {
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
            /** Sort Order */
            sort_order: number;
        };
        /** CategoryVisitCount */
        CategoryVisitCount: {
            /** Category */
            category?: string | null;
            /** Season Year */
            season_year?: number | null;
            /** Count */
            count: number;
        };
        /**
         * ComparisonCount
         * @description One row in the top-comparisons aggregation. Slugs are normalized
         *     alphabetically by the track endpoint so (A,B) and (B,A) bucket as
         *     one pair.
         */
        ComparisonCount: {
            /** Slug A */
            slug_a: string;
            /** Slug B */
            slug_b: string;
            /** Count */
            count: number;
        };
        /** DeviceCount */
        DeviceCount: {
            /** Device Type */
            device_type: string;
            /** Count */
            count: number;
        };
        /**
         * EventDetailOut
         * @description Single race plus the categories that compete in it.
         */
        EventDetailOut: {
            season: components["schemas"]["SeasonRef"];
            event: components["schemas"]["EventRef"];
            /** Categories */
            categories: components["schemas"]["CategoryRef"][];
        };
        /** EventListOut */
        EventListOut: {
            season: components["schemas"]["SeasonRef"];
            /** Events */
            events: components["schemas"]["EventRef"][];
        };
        /** EventRef */
        EventRef: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Event Date */
            event_date?: string | null;
            /** Location */
            location?: string | null;
            /** Sort Order */
            sort_order: number;
            /** Event Type */
            event_type?: string | null;
            /** Facebook Event Url */
            facebook_event_url?: string | null;
            /** Description */
            description?: string | null;
        };
        /** EventResultRowOut */
        EventResultRowOut: {
            /** Position */
            position?: number | null;
            rider: components["schemas"]["RiderRef"];
            /** Points */
            points?: number | null;
            /** Time Ms */
            time_ms?: number | null;
            /** Gap Ms */
            gap_ms?: number | null;
            /** Gps Penalty Ms */
            gps_penalty_ms?: number | null;
            /** Laps */
            laps?: number | null;
            /** Cp Count */
            cp_count?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** EventResultsOut */
        EventResultsOut: {
            season: components["schemas"]["SeasonRef"];
            category: components["schemas"]["CategoryRef"];
            event: components["schemas"]["EventRef"];
            /** Rows */
            rows: components["schemas"]["EventResultRowOut"][];
        };
        /**
         * GlobalRiderSearchOut
         * @description Response for /api/riders/search (cross-season).
         *
         *     Each row carries its own season_year, so the caller can render a
         *     year tag. Results are deduped by rider slug — a rider who raced in
         *     multiple seasons appears once, with the most recent (year, category).
         */
        GlobalRiderSearchOut: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["RiderSearchResultOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RaceVisitCount */
        RaceVisitCount: {
            /** Season Year */
            season_year?: number | null;
            /** Event Slug */
            event_slug: string;
            /** Count */
            count: number;
        };
        /** RecentVisit */
        RecentVisit: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Page */
            page: string;
            /** Category */
            category?: string | null;
            /** Season Year */
            season_year?: number | null;
            /** Event Slug */
            event_slug?: string | null;
            /** Rider Slug */
            rider_slug?: string | null;
            /** Device Type */
            device_type: string;
        };
        /**
         * RiderCareerOut
         * @description Response for /api/riders/career.
         *
         *     Groups every Rider row (across all seasons) whose name matches the
         *     queried slug, returning one summary row per (season_year, category).
         */
        RiderCareerOut: {
            /** Slug */
            slug: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Seasons */
            seasons: components["schemas"]["RiderCareerSeasonOut"][];
        };
        /**
         * RiderCareerSeasonOut
         * @description One row in a rider's multi-season history (P3 #17).
         *
         *     `results` carries every per-event row (already collapsed across days)
         *     so the rider profile page can render with a single API call.
         */
        RiderCareerSeasonOut: {
            /** Season Year */
            season_year: number;
            /** Race Number */
            race_number: number;
            category: components["schemas"]["CategoryRef"];
            /** Team */
            team?: string | null;
            /** Bike */
            bike?: string | null;
            /** Final Position */
            final_position?: number | null;
            /** Races Participated */
            races_participated: number;
            /** Total Points */
            total_points: number;
            /** Best Position */
            best_position?: number | null;
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["RiderResultOut"][];
        };
        /**
         * RiderDisambigEntryOut
         * @description One candidate in the disambiguation list (two riders sharing a race number).
         */
        RiderDisambigEntryOut: {
            rider: components["schemas"]["RiderRef"];
            /** Categories */
            categories: components["schemas"]["CategoryRef"][];
        };
        /**
         * RiderDisambigOut
         * @description Response when multiple (first, last) pairs share a race number in a season.
         */
        RiderDisambigOut: {
            season: components["schemas"]["SeasonRef"];
            /** Race Number */
            race_number: number;
            /** Candidates */
            candidates: components["schemas"]["RiderDisambigEntryOut"][];
        };
        /**
         * RiderEventEntryOut
         * @description A rider's result in a single event within the leaderboard table.
         */
        RiderEventEntryOut: {
            /** Event Slug */
            event_slug: string;
            /** Points */
            points: number;
            /** Position */
            position: number;
        };
        /**
         * RiderProfileOut
         * @description Singular rider page: header meta + every result this season.
         */
        RiderProfileOut: {
            season: components["schemas"]["SeasonRef"];
            rider: components["schemas"]["RiderRef"];
            /** Categories */
            categories: components["schemas"]["CategoryRef"][];
            /** Results */
            results: components["schemas"]["RiderResultOut"][];
            /** Total Events */
            total_events: number;
        };
        /**
         * RiderRef
         * @description Uniquely identifies a rider within a season.
         *
         *     ``slug`` is computed on the backend (``app.slug.rider_slug``) and MUST
         *     be consumed by the frontend verbatim — never recomputed client-side.
         */
        RiderRef: {
            /** Race Number */
            race_number: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Slug */
            slug: string;
            /** Team */
            team?: string | null;
            /** Bike */
            bike?: string | null;
        };
        /**
         * RiderResultOut
         * @description A single (event, category) result within a rider's season profile.
         */
        RiderResultOut: {
            event: components["schemas"]["EventRef"];
            category: components["schemas"]["CategoryRef"];
            /** Position */
            position?: number | null;
            /** Points */
            points?: number | null;
            /** Time Ms */
            time_ms?: number | null;
            /** Gap Ms */
            gap_ms?: number | null;
            /** Gps Penalty Ms */
            gps_penalty_ms?: number | null;
            /** Laps */
            laps?: number | null;
        };
        /**
         * RiderSearchOut
         * @description Response for /api/seasons/{year}/riders/search.
         */
        RiderSearchOut: {
            season: components["schemas"]["SeasonRef"];
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["RiderSearchResultOut"][];
        };
        /**
         * RiderSearchResultOut
         * @description One row in the rider search response.
         *
         *     `category` is the first category the rider competes in (riders may
         *     appear in multiple categories per season; UI links to the first).
         */
        RiderSearchResultOut: {
            rider: components["schemas"]["RiderRef"];
            category: components["schemas"]["CategoryRef"];
            /** Season Year */
            season_year: number;
        };
        /** RiderVisitCount */
        RiderVisitCount: {
            /** Season Year */
            season_year?: number | null;
            /** Rider Slug */
            rider_slug: string;
            /** Count */
            count: number;
        };
        /**
         * SeasonDetailOut
         * @description Season metadata plus its categories and events.
         */
        SeasonDetailOut: {
            season: components["schemas"]["SeasonRef"];
            /** Categories */
            categories: components["schemas"]["CategoryRef"][];
            /** Events */
            events: components["schemas"]["EventRef"][];
            /** Rider Count */
            rider_count: number;
        };
        /** SeasonListOut */
        SeasonListOut: {
            /** Seasons */
            seasons: components["schemas"]["SeasonRef"][];
        };
        /** SeasonRef */
        SeasonRef: {
            /** Year */
            year: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Is Current */
            is_current: boolean;
            /** Championship Format */
            championship_format: string;
        };
        /**
         * StandingsOut
         * @description Full leaderboard response for one category within one season.
         */
        StandingsOut: {
            season: components["schemas"]["SeasonRef"];
            category: components["schemas"]["CategoryRef"];
            /** Events */
            events: components["schemas"]["EventRef"][];
            /** Rows */
            rows: components["schemas"]["StandingsRowOut"][];
            /** Championship Format */
            championship_format: string;
        };
        /** StandingsRowOut */
        StandingsRowOut: {
            /** Final Position */
            final_position: number;
            rider: components["schemas"]["RiderRef"];
            /** Events */
            events: components["schemas"]["RiderEventEntryOut"][];
            /** Total Points */
            total_points: number;
            /** Races Participated */
            races_participated: number;
            /** Best Position */
            best_position?: number | null;
            /** Worst Event Slug */
            worst_event_slug?: string | null;
            /** Worst Dropped */
            worst_dropped?: number | null;
        };
        /** StatsOut */
        StatsOut: {
            /** Total Visits */
            total_visits: number;
            /** Unique Visitors Today */
            unique_visitors_today: number;
            /** Unique Visitors 7D */
            unique_visitors_7d: number;
            /** Unique Visitors 30D */
            unique_visitors_30d: number;
            /** Sessions Today */
            sessions_today: number;
            /** Avg Session Seconds */
            avg_session_seconds: number;
            /** Devices */
            devices: components["schemas"]["DeviceCount"][];
            /** Per Category */
            per_category: components["schemas"]["CategoryVisitCount"][];
            /** Per Race */
            per_race: components["schemas"]["RaceVisitCount"][];
            /** Per Rider */
            per_rider: components["schemas"]["RiderVisitCount"][];
            /** Top Comparisons */
            top_comparisons: components["schemas"]["ComparisonCount"][];
            /** Recent */
            recent: components["schemas"]["RecentVisit"][];
        };
        /**
         * TrackIn
         * @description One visit event from the frontend router's afterEach hook.
         *
         *     Payload size is capped by middleware; per-IP rate limit is applied by slowapi.
         */
        TrackIn: {
            /** Page */
            page: string;
            /** Category */
            category?: string | null;
            /** Season Year */
            season_year?: number | null;
            /** Event Slug */
            event_slug?: string | null;
            /** Rider Slug */
            rider_slug?: string | null;
            /** Compared With Slug */
            compared_with_slug?: string | null;
        };
        /** TrackOut */
        TrackOut: {
            /** Ok */
            ok: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_seasons_api_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonListOut"];
                };
            };
        };
    };
    get_season_detail_api_seasons__year__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_api_seasons__year__standings__category_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_code: string;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_races_api_seasons__year__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_detail_api_seasons__year__events__event_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_slug: string;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_results_api_seasons__year__categories__category_code__events__event_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_slug: string;
                category_code: string;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_riders_api_seasons__year__riders_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_riders_sharing_number_api_seasons__year__riders__race_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_number: number;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderDisambigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rider_api_seasons__year__riders__race_number___slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_number: number;
                slug: string;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rider_career_api_riders_career_get: {
        parameters: {
            query: {
                slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderCareerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_riders_global_api_riders_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalRiderSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    track_visit_api_track_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
