/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_api_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season Detail */
        get: operations["get_season_detail_api_seasons__year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/standings/{category_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_api_seasons__year__standings__category_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Races */
        get: operations["list_races_api_seasons__year__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/events/{event_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Race Detail */
        get: operations["get_race_detail_api_seasons__year__events__event_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/categories/{category_code}/events/{event_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Race Results */
        get: operations["get_race_results_api_seasons__year__categories__category_code__events__event_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/riders/{race_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Riders Sharing Number
         * @description Returns every (first, last) pair sharing ``race_number`` in this season.
         *
         *     Use case: when multiple people race with the same number (common when a
         *     number is shared across categories or reissued), the frontend shows a
         *     disambiguation page before resolving to a singular rider.
         */
        get: operations["list_riders_sharing_number_api_seasons__year__riders__race_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/riders/{race_number}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rider
         * @description Resolves the rider matching (season, race_number, slug) to a full profile.
         *
         *     404 if the race_number doesn't exist in the season, the slug doesn't match any
         *     (first, last) pair with that number, or the rider has no results.
         */
        get: operations["get_rider_api_seasons__year__riders__race_number___slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Track Visit */
        post: operations["track_visit_api_track_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryRef */
        CategoryRef: {
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
            /** Sort Order */
            sort_order: number;
        };
        /** CategoryVisitCount */
        CategoryVisitCount: {
            /** Category */
            category?: string | null;
            /** Season Year */
            season_year?: number | null;
            /** Count */
            count: number;
        };
        /** DeviceCount */
        DeviceCount: {
            /** Device Type */
            device_type: string;
            /** Count */
            count: number;
        };
        /**
         * EventDetailOut
         * @description Single race plus the categories that compete in it.
         */
        EventDetailOut: {
            season: components["schemas"]["SeasonRef"];
            event: components["schemas"]["EventRef"];
            /** Categories */
            categories: components["schemas"]["CategoryRef"][];
        };
        /** EventListOut */
        EventListOut: {
            season: components["schemas"]["SeasonRef"];
            /** Events */
            events: components["schemas"]["EventRef"][];
        };
        /** EventRef */
        EventRef: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Event Date */
            event_date?: string | null;
            /** Location */
            location?: string | null;
            /** Sort Order */
            sort_order: number;
            /** Event Type */
            event_type?: string | null;
        };
        /** EventResultRowOut */
        EventResultRowOut: {
            /** Position */
            position?: number | null;
            rider: components["schemas"]["RiderRef"];
            /** Points */
            points?: number | null;
            /** Time Ms */
            time_ms?: number | null;
            /** Gap Ms */
            gap_ms?: number | null;
            /** Gps Penalty Ms */
            gps_penalty_ms?: number | null;
            /** Laps */
            laps?: number | null;
            /** Cp Count */
            cp_count?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** EventResultsOut */
        EventResultsOut: {
            season: components["schemas"]["SeasonRef"];
            category: components["schemas"]["CategoryRef"];
            event: components["schemas"]["EventRef"];
            /** Rows */
            rows: components["schemas"]["EventResultRowOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RecentVisit */
        RecentVisit: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Page */
            page: string;
            /** Category */
            category?: string | null;
            /** Season Year */
            season_year?: number | null;
            /** Device Type */
            device_type: string;
        };
        /**
         * RiderDisambigEntryOut
         * @description One candidate in the disambiguation list (two riders sharing a race number).
         */
        RiderDisambigEntryOut: {
            rider: components["schemas"]["RiderRef"];
            /** Categories */
            categories: components["schemas"]["CategoryRef"][];
        };
        /**
         * RiderDisambigOut
         * @description Response when multiple (first, last) pairs share a race number in a season.
         */
        RiderDisambigOut: {
            season: components["schemas"]["SeasonRef"];
            /** Race Number */
            race_number: number;
            /** Candidates */
            candidates: components["schemas"]["RiderDisambigEntryOut"][];
        };
        /**
         * RiderEventEntryOut
         * @description A rider's result in a single event within the leaderboard table.
         */
        RiderEventEntryOut: {
            /** Event Slug */
            event_slug: string;
            /** Points */
            points: number;
            /** Position */
            position: number;
        };
        /**
         * RiderProfileOut
         * @description Singular rider page: header meta + every result this season.
         */
        RiderProfileOut: {
            season: components["schemas"]["SeasonRef"];
            rider: components["schemas"]["RiderRef"];
            /** Categories */
            categories: components["schemas"]["CategoryRef"][];
            /** Results */
            results: components["schemas"]["RiderResultOut"][];
            /** Total Events */
            total_events: number;
        };
        /**
         * RiderRef
         * @description Uniquely identifies a rider within a season.
         *
         *     ``slug`` is computed on the backend (``app.slug.rider_slug``) and MUST
         *     be consumed by the frontend verbatim — never recomputed client-side.
         */
        RiderRef: {
            /** Race Number */
            race_number: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Slug */
            slug: string;
            /** Team */
            team?: string | null;
            /** Bike */
            bike?: string | null;
        };
        /**
         * RiderResultOut
         * @description A single (event, category) result within a rider's season profile.
         */
        RiderResultOut: {
            event: components["schemas"]["EventRef"];
            category: components["schemas"]["CategoryRef"];
            /** Position */
            position?: number | null;
            /** Points */
            points?: number | null;
            /** Time Ms */
            time_ms?: number | null;
            /** Gap Ms */
            gap_ms?: number | null;
            /** Gps Penalty Ms */
            gps_penalty_ms?: number | null;
            /** Laps */
            laps?: number | null;
        };
        /**
         * SeasonDetailOut
         * @description Season metadata plus its categories and events.
         */
        SeasonDetailOut: {
            season: components["schemas"]["SeasonRef"];
            /** Categories */
            categories: components["schemas"]["CategoryRef"][];
            /** Events */
            events: components["schemas"]["EventRef"][];
        };
        /** SeasonListOut */
        SeasonListOut: {
            /** Seasons */
            seasons: components["schemas"]["SeasonRef"][];
        };
        /** SeasonRef */
        SeasonRef: {
            /** Year */
            year: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Is Current */
            is_current: boolean;
            /** Championship Format */
            championship_format: string;
        };
        /**
         * StandingsOut
         * @description Full leaderboard response for one category within one season.
         */
        StandingsOut: {
            season: components["schemas"]["SeasonRef"];
            category: components["schemas"]["CategoryRef"];
            /** Events */
            events: components["schemas"]["EventRef"][];
            /** Rows */
            rows: components["schemas"]["StandingsRowOut"][];
            /** Championship Format */
            championship_format: string;
        };
        /** StandingsRowOut */
        StandingsRowOut: {
            /** Final Position */
            final_position: number;
            rider: components["schemas"]["RiderRef"];
            /** Events */
            events: components["schemas"]["RiderEventEntryOut"][];
            /** Total Points */
            total_points: number;
            /** Races Participated */
            races_participated: number;
            /** Best Position */
            best_position: number;
            /** Worst Event Slug */
            worst_event_slug?: string | null;
            /** Worst Dropped */
            worst_dropped?: number | null;
        };
        /** StatsOut */
        StatsOut: {
            /** Total Visits */
            total_visits: number;
            /** Devices */
            devices: components["schemas"]["DeviceCount"][];
            /** Per Category */
            per_category: components["schemas"]["CategoryVisitCount"][];
            /** Recent */
            recent: components["schemas"]["RecentVisit"][];
        };
        /**
         * TrackIn
         * @description One visit event from the frontend router's afterEach hook.
         *
         *     Payload size is capped by middleware; per-IP rate limit is applied by slowapi.
         */
        TrackIn: {
            /** Page */
            page: string;
            /** Category */
            category?: string | null;
            /** Season Year */
            season_year?: number | null;
        };
        /** TrackOut */
        TrackOut: {
            /** Ok */
            ok: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_seasons_api_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonListOut"];
                };
            };
        };
    };
    get_season_detail_api_seasons__year__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_api_seasons__year__standings__category_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_code: string;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_races_api_seasons__year__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_detail_api_seasons__year__events__event_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_slug: string;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_results_api_seasons__year__categories__category_code__events__event_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_slug: string;
                category_code: string;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_riders_sharing_number_api_seasons__year__riders__race_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_number: number;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderDisambigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rider_api_seasons__year__riders__race_number___slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                race_number: number;
                slug: string;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    track_visit_api_track_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
